services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=host.docker.internal
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=Xing@1225
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      # 禁用认证 - 后续需要启用
      - NACOS_AUTH_ENABLED=false
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/conf:/home/nacos/conf
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped

  kafka-registry:
    image: openjdk:11-jre-slim
    container_name: kafka-registry
    depends_on:
      - kafka
      - nacos
    environment:
      - NACOS_SERVER_ADDR=nacos:8848
      - KAFKA_SERVER_ADDR=kafka:9092
      - SERVICE_NAME=kafka-service
      - SERVICE_IP=kafka
      - SERVICE_PORT=9092
    command: |
      sh -c "
        echo 'Waiting for services to be ready...'
        sleep 30
        echo 'Registering Kafka service to Nacos...'
        curl -X POST 'http://nacos:8848/nacos/v1/ns/instance' \
          -d 'serviceName=kafka-service' \
          -d 'ip=kafka' \
          -d 'port=9092' \
          -d 'namespaceId=public' \
          -d 'groupName=DEFAULT_GROUP' \
          -d 'metadata={"type":"message-queue","version":"3.7.0","description":"Apache Kafka Message Queue"}'
        echo 'Kafka service registered successfully!'
        tail -f /dev/null
      "
    restart: unless-stopped

# 使用host网络模式，不需要自定义网络
# networks:
#   linkr-network:
#     driver: bridge

volumes:
  kafka-data:
