server:
  port: 8080

spring:
  application:
    name: admin-module
  # 添加配置导入，解决Spring Cloud配置问题
  # config:
  #   import: optional:nacos:
  # 禁用Spring Security自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linkr_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      continue-on-error: true
  cloud:
    nacos:
      discovery:
        # Nacos服务器地址
        server-addr: localhost:8848
        # 命名空间，使用默认public
        namespace: public
        # 服务组，使用默认DEFAULT_GROUP
        group: DEFAULT_GROUP
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register-enabled: true
        # 临时实例（服务停止后自动注销）
        ephemeral: true
        # 心跳间隔（毫秒）
        heart-beat-interval: 5000
        # 心跳超时时间（毫秒）
        heart-beat-timeout: 15000
        # IP删除超时时间（毫秒）
        ip-delete-timeout: 30000
        # 注册失败时是否快速失败
        fail-fast: false
        # 注册超时时间（毫秒）
        register-timeout: 10000
        # 服务元数据
        metadata:
          version: 1.0.0
          environment: dev
          description: Admin management service
          # 自定义元数据
          management.port: 8080
          management.context-path: /actuator
        # 集群名称
        cluster-name: DEFAULT
        # 服务权重
        weight: 1
      config:
        # Nacos服务器地址
        server-addr: 127.0.0.1:8848
        # 命名空间
        namespace: public
        # 配置组
        group: DEFAULT_GROUP
        # 配置文件扩展名
        file-extension: yml
        # 启用配置中心
        enabled: false
        # 启用配置刷新
        refresh-enabled: false
        # 配置超时时间
        timeout: 3000
        # 配置重试时间
        retry-time: 3000
        # 长轮询超时时间
        long-poll-timeout: 460
        # 最大重试次数
        max-retry: 3
        import-check:
          enabled: false

# Kafka配置
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

# Kafka主题配置
kafka:
  topic:
    log: admin-logs

# Spring Security开关配置
security:
  enabled: false

# 健康检查和监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    com.aleks.linkrmix: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:com/aleks/linkrmix/admin/mapper/*.xml
  type-aliases-package: com.aleks.linkrmix.admin.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false


