version: '3.8'

services:
  # Elasticsearch 8.11.0 - 轻量级单节点配置（自定义镜像，已移除 S3 插件）
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elk-elasticsearch
    environment:
      # 单节点模式
      - discovery.type=single-node
      # 禁用安全功能（开发环境）
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      # 内存配置 - 轻量级
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g -Daws.accessKeyId= -Daws.secretKey= -Daws.region= -Dcom.amazonaws.sdk.disableEc2Metadata=true"
      # 网络配置
      - network.host=0.0.0.0
      - http.port=9200
      - transport.port=9300
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elk-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kibana 8.11.0 - 轻量级配置
  kibana:
    image: kibana:8.11.0
    container_name: elk-kibana
    environment:
      # Elasticsearch连接配置
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # 禁用安全功能
      - xpack.security.enabled=false
      # 内存配置
      - "NODE_OPTIONS=--max-old-space-size=512"
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Filebeat 8.11.0 - 轻量级日志收集
  filebeat:
    image: filebeat:8.11.0
    container_name: elk-filebeat
    user: root
    environment:
      # 配置文件路径
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/modules.d:/usr/share/filebeat/modules.d:ro
      # 挂载应用日志目录
      - ../linkr-server/logs:/var/log/app:ro
      - ../docker-config/nacos/logs:/var/log/nacos:ro
      # 系统日志（Linux）
      - /var/log:/var/log/host:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - elk-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    command: filebeat -e -strict.perms=false

volumes:
  elasticsearch_data:
    driver: local

networks:
  elk-network:
    driver: bridge
